name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install -r requirements.txt
    - run: pytest
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit (SAST)
      run: bandit -r .

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v2
    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v2
